### ISSUE TITLE
Items aren't actually deleted when the script is run

### ISSUE THREAD

**Issue by nlawrence22** [JamaSoftware/deleteByDocumentKey#1]
When the script runs, it claims it's deleting items, but no items are actually removed from Jama.  For example:

```
nlawrence$ python Main.py 
deleting item with id: 1859 and documentKey: ['AGILE_-BUG-1
deleting item with id: 1860 and documentKey: ['AGILE_-BUG-2
Total number of items deleted: 2
ToTal number of items ignored: 0
done
```

And yet, those items still exist in my instance.  It looks like there's an issue in the delete code, where we're getting items instead of deleting them.  I'm working on a pull request now.

**Comment by ibilal-jama** [comment]
Fixed the bug causing items to not be deleted. Should work now. Thanks for flagging this @nlawrence22
